class IntuivaApp {
    constructor() {
        this.currentQuestionIndex = 0;
        this.answers = {};
        this.tasks = [];
        this.kanbanBoard = null;
        this.isGeneratingTasks = false;
        this.isGeneratingReport = false;
        this.currentScreen = 'onboarding';
        this.currentLanguage = this.detectLanguage();
        this.currentProject = null;
        this.savedProjects = [];
        this.autoSaveInterval = null;
        this.autoSaveEnabled = true;
        this.isCompactView = false;
        
        this.init();
    }
    
    detectLanguage() {
        const savedLang = localStorage.getItem('intuiva-language');
        if (savedLang) return savedLang;
        
        const browserLang = navigator.language || navigator.userLanguage;
        if (browserLang.startsWith('tr')) return 'tr';
        
        return 'en';
    }
    
    t(key, params = {}) {
        // Get translation from window object or use fallback
        let translation = window.TRANSLATIONS?.[this.currentLanguage]?.[key] || 
                        window.TRANSLATIONS?.['en']?.[key] || 
                        key;
        
        // Handle missing translations with fallbacks
        if (translation === key) {
            // Provide basic fallback translations
            const fallbacks = {
                'board.noTasks': 'No tasks yet',
                'board.addOrGenerate': 'Add a task or generate with AI',
                'help.click': 'Click to edit',
                'help.delete': 'Delete task',
                'priority.high': 'High',
                'priority.medium': 'Medium',
                'priority.low': 'Low',
                'priority.critical': 'Critical',
                'status.todo': 'To Do',
                'status.inprogress': 'In Progress',
                'status.done': 'Done',
                'confirm.deleteTask': 'Are you sure you want to delete this task?',
                'toast.taskDeleted': 'Task deleted successfully',
                'modal.editTask': 'Edit Task',
                'modal.addTask': 'Add Task',
                'toast.taskUpdated': 'Task updated successfully',
                'toast.taskAdded': 'Task added successfully',
                'confirm.clearAll': 'Are you sure you want to clear all tasks? This cannot be undone.',
                'toast.allCleared': 'All tasks cleared successfully',
                'error.taskTitleRequired': 'Task title is required',
                'ai.generatingTasks': 'Generating tasks with AI...',
                'ai.generatedSuccess': 'Tasks generated successfully!',
                'ai.generatedFallback': 'Using recommended tasks',
                'ai.regeneratingTasks': 'Regenerating tasks...',
                'ai.regeneratedSuccess': 'Tasks regenerated successfully!',
                'ai.regeneratedFallback': 'Using enhanced tasks',
                'ai.generatingReport': 'Generating project report...',
                'ai.reportGenerated': 'Report generated successfully!',
                'ai.reportGeneratedLocal': 'Generated local report',
                'project.defaultName': 'Project {date}',
                'toast.newProjectCreated': 'New project created',
                'error.projectNameRequired': 'Project name is required',
                'toast.projectSaved': 'Project saved successfully',
                'toast.projectLoaded': 'Project loaded: {name}',
                'confirm.deleteProject': 'Are you sure you want to delete this project?',
                'toast.projectDeleted': 'Project deleted successfully',
                'error.projectNotFound': 'Project not found',
                'error.deleteFailed': 'Failed to delete project',
                'toast.projectImported': 'Project imported successfully',
                'error.importFailed': 'Failed to import project',
                'toast.projectExported': 'Project exported successfully',
                'toast.themeSwitched': 'Switched to {theme} theme',
                'theme.dark': 'dark',
                'theme.light': 'light',
                'toast.compactMode': 'Compact mode {mode}',
                'on': 'on',
                'off': 'off',
                'toast.languageChanged': 'Language changed to {language}',
                'language.en': 'English',
                'language.tr': 'Turkish',
                'report.generatedOn': 'Generated on',
                'report.tasks': 'tasks',
                'report.answersAnalyzed': 'answers analyzed',
                'report.aiInsights': 'AI-powered insights based on your input',
                'report.generatedBy': 'Generated by Intuiva',
                'report.totalTasks': 'Total Tasks',
                'report.completed': 'Completed',
                'report.highPriority': 'High Priority',
                'report.questionsAnswered': 'Questions Answered',
                'report.generatedByIntuiva': 'Generated by Intuiva Project Manager',
                'report.creator': 'Creator',
                'toast.pdfDownloaded': 'Report downloaded successfully',
                'error.noReport': 'No report available. Generate one first.',
                'project.noProjects': 'No projects yet'
            };
            
            translation = fallbacks[key] || key;
        }
        
        // Replace parameters
        Object.keys(params).forEach(param => {
            translation = translation.replace(`{{${param}}}`, params[param]);
        });
        
        return translation;
    }

    init() {
        // Initialize screens
        this.screens = {
            onboarding: document.getElementById('onboarding'),
            questionnaire: document.getElementById('questionnaire'),
            kanbanBoard: document.getElementById('kanbanBoard')
        };
        
        // Make translation function available globally
        window.intuivaTranslation = (key, params) => this.t(key, params);
        
        // Initialize all components
        this.initButtons();
        this.initNavigation();
        this.initQuestionnaire();
        this.initModals();
        this.initTheme();
        this.initProjectManagement();
        this.initKeyboardShortcuts();
        this.initCompactView();
        
        this.showScreen('onboarding');
        this.savedProjects = this.getSavedProjects();
        this.updateSavedProjectsDropdown();
        
        // Apply language after everything is initialized
        setTimeout(() => {
            this.applyLanguage();
            const langSelector = document.getElementById('languageSelector');
            if (langSelector) {
                langSelector.value = this.currentLanguage;
            }
        }, 100);
        
        console.log('Intuiva App initialized successfully');
    }

    applyLanguage() {
        // Wait for DOM to be ready
        setTimeout(() => {
            // Update all translatable elements
            document.querySelectorAll('[data-i18n]').forEach(element => {
                const key = element.getAttribute('data-i18n');
                if (key) {
                    try {
                        const params = {};
                        element.getAttributeNames().forEach(attr => {
                            if (attr.startsWith('data-i18n-')) {
                                const paramName = attr.replace('data-i18n-', '');
                                params[paramName] = element.getAttribute(attr);
                            }
                        });
                        const text = this.t(key, params);
                        if (text) element.textContent = text;
                    } catch (error) {
                        console.warn('Translation failed for key:', key, error);
                    }
                }
            });
            
            // Update placeholders
            document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
                const key = element.getAttribute('data-i18n-placeholder');
                if (key) {
                    element.placeholder = this.t(key);
                }
            });
            
            // Update titles
            document.querySelectorAll('[data-i18n-title]').forEach(element => {
                const key = element.getAttribute('data-i18n-title');
                if (key) {
                    element.title = this.t(key);
                }
            });
            
            // Update page title
            document.title = this.t('app.title') || 'Intuiva - Project Manager';
            
            // Update language selector
            const langSelector = document.getElementById('languageSelector');
            if (langSelector) {
                langSelector.value = this.currentLanguage;
            }
            
            // Update question if on questionnaire screen
            if (this.currentScreen === 'questionnaire' && this.questions) {
                this.loadQuestion(this.currentQuestionIndex);
            }
            
            // Update kanban board if it exists
            if (this.kanbanBoard) {
                this.kanbanBoard.t = (key, params) => this.t(key, params);
                this.kanbanBoard.renderTasks();
            }
            
            // Update stats
            this.updateStats();
        }, 0);
    }
    
    initProjectManagement() {
        // Load the most recent project if exists
        this.savedProjects = this.getSavedProjects();
        if (this.savedProjects.length > 0) {
            const mostRecent = this.savedProjects.sort((a, b) => 
                new Date(b.updatedAt) - new Date(a.updatedAt)
            )[0];
            this.currentProject = mostRecent;
            this.loadProject(mostRecent.id);
        }
        
        // Start auto-save interval
        this.startAutoSave();
        
        // Update saved time display
        this.updateLastSavedTime();
    }
    
    initButtons() {
        // Start button
        const startBtn = document.getElementById('startBtn');
        if (startBtn) {
            startBtn.addEventListener('click', () => {
                this.createNewProject();
            });
        }
        
        // Load project button
        const loadProjectBtn = document.getElementById('loadProjectBtn');
        if (loadProjectBtn) {
            loadProjectBtn.addEventListener('click', () => {
                this.showLoadProjectModal();
            });
        }
        
        // Home button
        const homeBtn = document.getElementById('homeBtn');
        if (homeBtn) {
            homeBtn.addEventListener('click', (e) => {
                e.preventDefault();
                this.navigateTo('onboarding');
            });
        }
        
        // Saved projects dropdown
        const savedProjectsBtn = document.getElementById('savedProjectsBtn');
        if (savedProjectsBtn) {
            savedProjectsBtn.addEventListener('click', () => {
                this.toggleSavedProjectsDropdown();
            });
        }
        
        // Clear All button
        const clearAllBtn = document.getElementById('clearAllBtn');
        if (clearAllBtn) {
            clearAllBtn.addEventListener('click', () => {
                if (confirm(this.t('confirm.clearAll'))) {
                    this.tasks = [];
                    if (this.kanbanBoard) {
                        this.kanbanBoard.clearTasks();
                    }
                    this.updateStats();
                    this.saveProject();
                    this.showToast(this.t('toast.allCleared'), 'info');
                }
            });
        }
        
        // Navigation buttons
        const prevBtn = document.getElementById('prevBtn');
        if (prevBtn) {
            prevBtn.addEventListener('click', () => this.prevQuestion());
        }
        
        const nextBtn = document.getElementById('nextBtn');
        if (nextBtn) {
            nextBtn.addEventListener('click', () => this.nextQuestion());
        }
        
        // Question action buttons
        const skipQuestionBtn = document.getElementById('skipQuestionBtn');
        if (skipQuestionBtn) {
            skipQuestionBtn.addEventListener('click', () => this.skipQuestion());
        }
        
        const notAnswerBtn = document.getElementById('notAnswerBtn');
        if (notAnswerBtn) {
            notAnswerBtn.addEventListener('click', () => this.markAsNotApplicable());
        }
        
        const clearBtn = document.getElementById('clearBtn');
        if (clearBtn) {
            clearBtn.addEventListener('click', () => this.clearAnswer());
        }
        
        // Board action buttons
        const addTaskBtn = document.getElementById('addTaskBtn');
        if (addTaskBtn) {
            addTaskBtn.addEventListener('click', () => this.openTaskModal());
        }
        
        const regenerateBtn = document.getElementById('regenerateBtn');
        if (regenerateBtn) {
            regenerateBtn.addEventListener('click', () => this.regenerateTasks());
        }
        
        const saveProjectBtn = document.getElementById('saveProjectBtn');
        if (saveProjectBtn) {
            saveProjectBtn.addEventListener('click', () => this.showSaveProjectModal());
        }
        
        const exportProjectBtn = document.getElementById('exportProjectBtn');
        if (exportProjectBtn) {
            exportProjectBtn.addEventListener('click', () => this.exportProject());
        }
        
        // Report buttons
        const generateReportBtn = document.getElementById('generateReportBtn');
        if (generateReportBtn) {
            generateReportBtn.addEventListener('click', () => this.generateProjectReport());
        }
        
        const generateReportPlaceholderBtn = document.getElementById('generateReportPlaceholderBtn');
        if (generateReportPlaceholderBtn) {
            generateReportPlaceholderBtn.addEventListener('click', () => this.generateProjectReport());
        }
        
        const downloadPdfBtn = document.getElementById('downloadPdfBtn');
        if (downloadPdfBtn) {
            downloadPdfBtn.addEventListener('click', () => this.downloadPdfReport());
        }
        
        // Add task buttons in columns
        document.querySelectorAll('.btn-add-task').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const column = e.currentTarget.dataset.column;
                this.openTaskModal(column);
            });
        });
        
        // Theme toggle
        const themeToggle = document.getElementById('themeToggle');
        if (themeToggle) {
            themeToggle.addEventListener('click', () => this.toggleTheme());
        }
        
        // Help button
        const helpBtn = document.getElementById('helpBtn');
        if (helpBtn) {
            helpBtn.addEventListener('click', () => {
                document.getElementById('helpModal')?.classList.add('active');
            });
        }
        
        // Language selector
        const langSelector = document.getElementById('languageSelector');
        if (langSelector) {
            langSelector.addEventListener('change', (e) => {
                this.setLanguage(e.target.value);
            });
        }
        
        // Back to questions button
        const backToQuestionsBtn = document.getElementById('backToQuestionsBtn');
        if (backToQuestionsBtn) {
            backToQuestionsBtn.addEventListener('click', () => {
                this.navigateTo('questionnaire');
            });
        }
        
        // Compact view toggle
        const compactToggle = document.getElementById('compactToggle');
        if (compactToggle) {
            compactToggle.addEventListener('click', () => this.toggleCompactView());
        }
        
        // Jump to start/end buttons
        const jumpToStartBtn = document.getElementById('jumpToStartBtn');
        if (jumpToStartBtn) {
            jumpToStartBtn.addEventListener('click', () => this.jumpToQuestion(0));
        }
        
        const jumpToEndBtn = document.getElementById('jumpToEndBtn');
        if (jumpToEndBtn) {
            jumpToEndBtn.addEventListener('click', () => this.jumpToQuestion(this.questions.length - 1));
        }
    }

    initNavigation() {
        document.querySelectorAll('.nav-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const screen = e.currentTarget.dataset.screen;
                this.navigateTo(screen);
            });
        });
        
        this.updateActiveNav();
    }

    navigateTo(screenName) {
        // Save current answer before navigating away
        if (this.currentScreen === 'questionnaire') {
            const answerInput = document.getElementById('answerInput');
            if (answerInput) {
                this.saveAnswer(answerInput.value);
            }
        }
        
        this.showScreen(screenName);
        this.currentScreen = screenName;
        this.updateActiveNav();
        
        if (screenName === 'questionnaire') {
            this.loadQuestion(this.currentQuestionIndex);
        }
        
        if (screenName === 'kanbanBoard') {
            this.initializeKanbanBoard();
            this.updateStats();
            this.updateLastSavedTime();
        }
    }

    initializeKanbanBoard() {
        if (!this.kanbanBoard) {
            this.kanbanBoard = new KanbanBoard(this.tasks, (key, params) => this.t(key, params));
        } else {
            this.kanbanBoard.tasks = this.tasks;
            this.kanbanBoard.t = (key, params) => this.t(key, params);
            this.kanbanBoard.renderTasks();
        }
    }

    updateActiveNav() {
        document.querySelectorAll('.nav-btn').forEach(btn => {
            if (btn.dataset.screen === this.currentScreen) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });
    }

    initQuestionnaire() {
        // Load questions based on language
        if (window.getQuestions) {
            this.questions = window.getQuestions(this.currentLanguage);
        } else if (window.QUESTIONS && window.QUESTIONS[this.currentLanguage]) {
            this.questions = window.QUESTIONS[this.currentLanguage];
        } else if (Array.isArray(window.QUESTIONS)) {
            this.questions = window.QUESTIONS;
        } else {
            this.questions = [];
            console.error('No questions found!');
        }
        
        this.totalQuestions = this.questions.length;
        
        const answerInput = document.getElementById('answerInput');
        if (answerInput) {
            answerInput.addEventListener('input', (e) => {
                this.saveAnswer(e.target.value);
                this.updateCharCounter();
            });
            
            // FIX: Enter key navigation - only navigate on Enter without Shift/Ctrl
            answerInput.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' && !e.shiftKey && !e.ctrlKey) {
                    e.preventDefault();
                    this.nextQuestion();
                } else if (e.ctrlKey && e.key === 'Enter') {
                    e.preventDefault();
                    this.nextQuestion();
                } else if (e.key === 'Escape') {
                    this.clearAnswer();
                }
            });
        }
    }

    initModals() {
        this.taskModal = document.getElementById('taskModal');
        this.taskForm = document.getElementById('taskForm');
        this.saveProjectModal = document.getElementById('saveProjectModal');
        this.saveProjectForm = document.getElementById('saveProjectForm');
        this.loadProjectModal = document.getElementById('loadProjectModal');
        
        // Close modal buttons
        document.querySelectorAll('.close-modal').forEach(btn => {
            btn.addEventListener('click', () => {
                document.querySelectorAll('.modal').forEach(modal => {
                    modal.classList.remove('active');
                });
                if (this.taskForm) this.taskForm.reset();
                if (this.saveProjectForm) this.saveProjectForm.reset();
            });
        });
        
        // Close modal on outside click
        document.querySelectorAll('.modal').forEach(modal => {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) {
                    modal.classList.remove('active');
                    if (this.taskForm) this.taskForm.reset();
                    if (this.saveProjectForm) this.saveProjectForm.reset();
                }
            });
        });
        
        // Task form submission
        if (this.taskForm) {
            this.taskForm.addEventListener('submit', (e) => {
                e.preventDefault();
                this.saveTask();
            });
        }
        
        // Save project form submission
        if (this.saveProjectForm) {
            this.saveProjectForm.addEventListener('submit', (e) => {
                e.preventDefault();
                this.saveProjectAs();
            });
        }
        
        // Import project button
        const importProjectBtn = document.getElementById('importProjectBtn');
        if (importProjectBtn) {
            importProjectBtn.addEventListener('click', () => {
                this.importProject();
            });
        }
        
        // Report toggle
        const reportToggle = document.getElementById('reportToggle');
        if (reportToggle) {
            reportToggle.addEventListener('click', () => {
                const reportContent = document.getElementById('reportContent');
                const icon = document.getElementById('reportToggleIcon');
                if (reportContent) {
                    reportContent.classList.toggle('collapsed');
                    icon.classList.toggle('fa-chevron-down');
                    icon.classList.toggle('fa-chevron-up');
                }
            });
        }
    }
    
    initKeyboardShortcuts() {
        document.addEventListener('keydown', (e) => {
            // Don't trigger if user is typing in an input
            if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') {
                return;
            }
            
            // Global shortcuts
            switch(e.key) {
                case 'n':
                    if (e.ctrlKey) {
                        e.preventDefault();
                        this.createNewProject();
                    }
                    break;
                case 's':
                    if (e.ctrlKey) {
                        e.preventDefault();
                        this.saveProject();
                    }
                    break;
                case 't':
                    if (e.ctrlKey) {
                        e.preventDefault();
                        this.toggleTheme();
                    }
                    break;
                case '?':
                    e.preventDefault();
                    document.getElementById('helpModal')?.classList.add('active');
                    break;
            }
        });
    }
    
    initCompactView() {
        this.isCompactView = localStorage.getItem('intuiva-compact') === 'true';
        this.applyCompactView();
    }
    
    initTheme() {
        const savedTheme = localStorage.getItem('intuiva-theme') || 'dark';
        document.documentElement.setAttribute('data-theme', savedTheme);
        
        const themeIcon = document.querySelector('#themeToggle i');
        if (themeIcon) {
            themeIcon.className = savedTheme === 'dark' ? 'fas fa-moon' : 'fas fa-sun';
        }
    }
    
    showScreen(screenName) {
        // Hide all screens
        Object.values(this.screens).forEach(screen => {
            if (screen) screen.classList.remove('active');
        });
        
        // Show selected screen
        if (this.screens[screenName]) {
            this.screens[screenName].classList.add('active');
            this.currentScreen = screenName;
        }
        
        this.updateActiveNav();
        
        // Show/hide project name display
        const projectNameDisplay = document.getElementById('projectNameDisplay');
        if (projectNameDisplay) {
            projectNameDisplay.style.display = screenName === 'kanbanBoard' ? 'block' : 'none';
        }
        
        // Focus on input if on questionnaire
        if (screenName === 'questionnaire') {
            setTimeout(() => {
                const answerInput = document.getElementById('answerInput');
                if (answerInput) answerInput.focus();
            }, 100);
        }
    }
    
    loadQuestion(index) {
        // Validate index
        if (index < 0) index = 0;
        if (index >= this.totalQuestions) {
            this.showKanbanBoard();
            return;
        }
        
        this.currentQuestionIndex = index;
        const question = this.questions[index];
        
        if (!question) {
            console.error('Question not found at index:', index);
            return;
        }
        
        // Update UI elements - safely check each element
        const questionNumber = document.getElementById('questionNumber');
        const questionTitle = document.getElementById('questionTitle');
        const questionText = document.getElementById('questionText');
        const categoryTitle = document.getElementById('categoryTitle');
        const progressFill = document.getElementById('progressFill');
        const progressText = document.getElementById('progressText');
        const answerInput = document.getElementById('answerInput');
        const prevBtn = document.getElementById('prevBtn');
        const nextBtn = document.getElementById('nextBtn');
        const nextBtnText = nextBtn?.querySelector('span');
        
        if (questionNumber) questionNumber.textContent = `Q${index + 1}`;
        if (questionTitle) questionTitle.textContent = question.category || 'Question';
        if (questionText) questionText.textContent = question.text || '';
        if (categoryTitle) categoryTitle.textContent = question.category || 'Category';
        
        // Update progress
        if (progressFill && progressText) {
            const progress = ((index + 1) / this.totalQuestions) * 100;
            progressFill.style.width = `${progress}%`;
            progressText.textContent = `${index + 1} / ${this.totalQuestions}`;
        }
        
        // Load saved answer
        if (answerInput) {
            answerInput.value = this.answers[index] || '';
            answerInput.focus();
        }
        
        // Update character counter
        this.updateCharCounter();
        
        // Update button states
        if (prevBtn) prevBtn.disabled = index === 0;
        
        // Update next button text for last question
        if (nextBtnText) {
            if (index === this.totalQuestions - 1) {
                nextBtnText.textContent = 'Generate Board';
            } else {
                nextBtnText.textContent = 'Next';
            }
        }
        
        // Update question dots
        this.updateQuestionDots();
    }
    
    updateQuestionDots() {
        const dotsContainer = document.querySelector('.question-dots');
        if (!dotsContainer) return;
        
        dotsContainer.innerHTML = '';
        
        for (let i = 0; i < this.totalQuestions; i++) {
            const dot = document.createElement('div');
            dot.className = 'question-dot';
            
            if (i === this.currentQuestionIndex) {
                dot.classList.add('active');
            } else if (this.answers[i]) {
                if (this.answers[i] === '[Skipped]') {
                    dot.classList.add('skipped');
                } else if (this.answers[i] === '[Not Applicable]') {
                    dot.classList.add('skipped');
                } else {
                    dot.classList.add('answered');
                }
            }
            
            dot.title = `Question ${i + 1}`;
            dot.addEventListener('click', () => {
                this.loadQuestion(i);
            });
            
            dotsContainer.appendChild(dot);
        }
    }
    
    prevQuestion() {
        if (this.currentQuestionIndex > 0) {
            this.saveCurrentAnswer();
            this.loadQuestion(this.currentQuestionIndex - 1);
        }
    }
    
    nextQuestion() {
        this.saveCurrentAnswer();
        
        if (this.currentQuestionIndex < this.totalQuestions - 1) {
            this.loadQuestion(this.currentQuestionIndex + 1);
        } else {
            this.generateTasksFromAnswers();
        }
    }
    
    saveCurrentAnswer() {
        const answerInput = document.getElementById('answerInput');
        if (answerInput) {
            this.saveAnswer(answerInput.value);
        }
    }
    
    skipQuestion() {
        this.answers[this.currentQuestionIndex] = '[Skipped]';
        this.nextQuestion();
    }
    
    markAsNotApplicable() {
        this.answers[this.currentQuestionIndex] = '[Not Applicable]';
        this.nextQuestion();
    }
    
    clearAnswer() {
        const answerInput = document.getElementById('answerInput');
        if (answerInput) {
            answerInput.value = '';
            delete this.answers[this.currentQuestionIndex];
            this.updateCharCounter();
            answerInput.focus();
        }
    }
    
    saveAnswer(answer) {
        if (answer && answer.trim()) {
            this.answers[this.currentQuestionIndex] = answer.trim();
        } else {
            delete this.answers[this.currentQuestionIndex];
        }
        
        // Auto-save if project exists
        if (this.currentProject) {
            this.saveProject();
        }
    }
    
    updateCharCounter() {
        const text = document.getElementById('answerInput')?.value || '';
        const charCount = text.length;
        const maxChars = 1000;
        
        const charCountElement = document.getElementById('charCount');
        if (charCountElement) {
            charCountElement.textContent = `${charCount}/${maxChars}`;
            
            if (charCount > maxChars * 0.9) {
                charCountElement.style.color = 'var(--color-error)';
            } else if (charCount > maxChars * 0.75) {
                charCountElement.style.color = 'var(--color-warning)';
            } else {
                charCountElement.style.color = 'var(--color-text-muted)';
            }
        }
    }
    
    async generateTasksFromAnswers() {
        if (this.isGeneratingTasks) return;
        
        this.isGeneratingTasks = true;
        
        // Show loading state
        this.showLoadingScreen(this.t('ai.generatingTasks'));
        
        try {
            const requestData = {
                answers: this.answers,
                questions: this.questions,
                language: this.currentLanguage,
                generateReport: true
            };

            const response = await fetch('https://intuivabackend-production.up.railway.app/api/generate-tasks', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(requestData)
            });

            const result = await response.json();

            if (result.success && result.tasks && result.tasks.length > 0) {
                this.tasks = result.tasks.map(task => ({
                    ...task,
                    id: this.generateId()
                }));
                
                // Store report if provided
                if (result.report) {
                    this.storeProjectReport(result.report);
                }
                
                this.showToast(this.t('ai.generatedSuccess'), 'success');
            } else {
                throw new Error('AI returned no tasks');
            }

        } catch (error) {
            console.warn('AI generation failed, using fallback:', error);
            this.tasks = this.generateTasksBasedOnAnswers();
            this.showToast(this.t('ai.generatedFallback'), 'info');
        } finally {
            this.hideLoadingScreen();
            this.saveProject();
            this.navigateTo('kanbanBoard');
            this.updateStats();
            this.isGeneratingTasks = false;
        }
    }
    
    showLoadingScreen(message) {
        const loadingScreen = document.createElement('div');
        loadingScreen.id = 'loadingScreen';
        loadingScreen.style.cssText = `
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: var(--color-bg);
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            z-index: 9999;
            gap: 1rem;
        `;
        
        loadingScreen.innerHTML = `
            <div class="loading" style="width: 40px; height: 40px; border-width: 3px;"></div>
            <p style="color: var(--color-text); font-size: 0.875rem;">${message}</p>
        `;
        
        document.body.appendChild(loadingScreen);
    }
    
    hideLoadingScreen() {
        const loadingScreen = document.getElementById('loadingScreen');
        if (loadingScreen) {
            loadingScreen.remove();
        }
    }
    
    generateTasksBasedOnAnswers() {
        const hasValidAnswers = Object.values(this.answers).some(answer => 
            answer && answer !== '[Skipped]' && answer !== '[Not Applicable]'
        );
        
        if (!hasValidAnswers) {
            return this.generateDefaultTasks();
        }
        
        const tasks = [];
        const isTurkish = this.currentLanguage === 'tr';
        
        Object.entries(this.answers).forEach(([index, answer]) => {
            if (answer === '[Skipped]' || answer === '[Not Applicable]') return;
            
            const question = this.questions[parseInt(index)];
            const category = question?.category || '';
            
            // Generate tasks based on answer length
            if (answer.length > 20) {
                tasks.push({
                    id: this.generateId(),
                    title: isTurkish ? 
                        `"${answer.substring(0, 30)}..." için eylem planı oluştur` :
                        `Create action plan for "${answer.substring(0, 30)}..."`,
                    description: isTurkish ?
                        `Bu yanıttan çıkarımlar: ${answer.substring(0, 100)}` :
                        `Insights from this answer: ${answer.substring(0, 100)}`,
                    status: 'todo',
                    priority: 'medium',
                    tags: isTurkish ? ['analiz', 'planlama'] : ['analysis', 'planning']
                });
            }
        });
        
        // Add default tasks if not enough
        if (tasks.length < 3) {
            tasks.push(...this.generateDefaultTasks());
        }
        
        return tasks.slice(0, 8); // Limit to 8 tasks
    }
    
    generateDefaultTasks() {
        const isTurkish = this.currentLanguage === 'tr';
        
        return [
            {
                id: this.generateId(),
                title: isTurkish ? 'Proje hedeflerini tanımla' : 'Define project goals',
                description: isTurkish ?
                    'Projenin neyi başarmasını istediğini açıkça belirt' :
                    'Clearly state what you want the project to achieve',
                status: "todo",
                priority: "high",
                tags: isTurkish ? ['planlama', 'hedefler'] : ['planning', 'goals']
            },
            {
                id: this.generateId(),
                title: isTurkish ? 'Ana adımları belirle' : 'Identify key steps',
                description: isTurkish ?
                    'Başarıya götürecek temel adımları listeleyin' :
                    'List the fundamental steps that will lead to success',
                status: "todo",
                priority: "medium",
                tags: isTurkish ? ['adımlar', 'yol haritası'] : ['steps', 'roadmap']
            },
            {
                id: this.generateId(),
                title: isTurkish ? 'Kaynakları planla' : 'Plan resources',
                description: isTurkish ?
                    'İhtiyaç duyulan zaman, bütçe ve insan kaynaklarını düşünün' :
                    'Consider required time, budget, and human resources',
                status: "todo",
                priority: "medium",
                tags: isTurkish ? ['kaynaklar', 'planlama'] : ['resources', 'planning']
            }
        ];
    }
    
    showKanbanBoard() {
        this.navigateTo('kanbanBoard');
    }
    
    updateStats() {
        if (!this.kanbanBoard) {
            this.initializeKanbanBoard();
        }
        
        const stats = this.kanbanBoard.getStats();
        
        const totalTasks = document.getElementById('totalTasks');
        const doneTasks = document.getElementById('doneTasks');
        const wipTasks = document.getElementById('wipTasks');
        const todoCount = document.getElementById('todoCount');
        const inprogressCount = document.getElementById('inprogressCount');
        const doneCount = document.getElementById('doneCount');
        
        if (totalTasks) totalTasks.textContent = stats.total;
        if (doneTasks) doneTasks.textContent = stats.done;
        if (wipTasks) wipTasks.textContent = stats.inProgress;
        if (todoCount) todoCount.textContent = stats.todo;
        if (inprogressCount) inprogressCount.textContent = stats.inProgress;
        if (doneCount) doneCount.textContent = stats.done;
    }
    
    openTaskModal(status = 'todo') {
        const modal = document.getElementById('taskModal');
        const modalTitle = document.getElementById('modalTitle');
        const taskStatus = document.getElementById('taskStatus');
        const taskTitle = document.getElementById('taskTitle');
        
        if (modal && modalTitle) {
            modalTitle.textContent = this.t('modal.addTask');
            if (taskStatus) taskStatus.value = status;
            modal.classList.add('active');
            if (taskTitle) setTimeout(() => taskTitle.focus(), 100);
        }
    }
    
    saveTask() {
        const title = document.getElementById('taskTitle')?.value?.trim();
        const description = document.getElementById('taskDescription')?.value?.trim();
        const priority = document.getElementById('taskPriority')?.value;
        const status = document.getElementById('taskStatus')?.value;
        const tags = document.getElementById('taskTags')?.value
            ?.split(',')
            .map(tag => tag.trim())
            .filter(tag => tag) || [];
        
        if (!title) {
            this.showToast(this.t('error.taskTitleRequired'), 'error');
            return;
        }
        
        const task = {
            id: this.generateId(),
            title,
            description,
            priority: priority || 'medium',
            status: status || 'todo',
            tags,
            createdAt: new Date().toISOString(),
            language: this.currentLanguage
        };
        
        if (this.kanbanBoard) {
            this.kanbanBoard.addTask(task);
            this.tasks.push(task);
            this.updateStats();
        }
        
        const modal = document.getElementById('taskModal');
        if (modal) modal.classList.remove('active');
        
        const taskForm = document.getElementById('taskForm');
        if (taskForm) taskForm.reset();
        
        this.showToast(this.t('toast.taskAdded'), 'success');
        this.saveProject();
    }
    
    async regenerateTasks() {
        if (this.isGeneratingTasks) return;
        
        this.isGeneratingTasks = true;
        this.showLoadingScreen(this.t('ai.regeneratingTasks'));
        
        try {
            const requestData = {
                answers: this.answers,
                questions: this.questions,
                language: this.currentLanguage,
                generateReport: true
            };

            const response = await fetch('https://intuivabackend-production.up.railway.app/api/generate-tasks', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(requestData)
            });

            const result = await response.json();

            if (result.success && result.tasks && result.tasks.length > 0) {
                this.tasks = result.tasks.map(task => ({
                    ...task,
                    id: this.generateId()
                }));
                
                if (this.kanbanBoard) {
                    this.kanbanBoard.clearTasks();
                    this.tasks.forEach(task => {
                        this.kanbanBoard.addTask(task);
                    });
                }
                
                // Store report if provided
                if (result.report) {
                    this.storeProjectReport(result.report);
                }
                
                this.showToast(this.t('ai.regeneratedSuccess'), 'success');
            } else {
                throw new Error('AI returned no tasks');
            }
            
        } catch (error) {
            console.warn('AI regeneration failed:', error);
            this.showToast(this.t('ai.regeneratedFallback'), 'info');
        } finally {
            this.hideLoadingScreen();
            this.updateStats();
            this.saveProject();
            this.isGeneratingTasks = false;
        }
    }
    
    createNewProject() {
        // Reset everything
        this.currentQuestionIndex = 0;
        this.answers = {};
        this.tasks = [];
        this.currentProject = {
            id: this.generateId(),
            name: this.t('project.defaultName', { date: new Date().toLocaleDateString() }),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            tasks: [],
            answers: {},
            language: this.currentLanguage
        };
        
        // Update board title
        const boardTitle = document.getElementById('boardTitle');
        if (boardTitle) {
            boardTitle.textContent = this.currentProject.name;
        }
        
        // Navigate to questionnaire
        this.navigateTo('questionnaire');
        this.loadQuestion(0);
        
        this.showToast(this.t('toast.newProjectCreated'), 'success');
    }
    
    saveProject() {
        if (!this.currentProject) {
            this.currentProject = {
                id: this.generateId(),
                name: this.t('project.defaultName', { date: new Date().toLocaleDateString() }),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                tasks: this.tasks,
                answers: this.answers,
                language: this.currentLanguage
            };
        }
        
        this.currentProject.tasks = this.tasks;
        this.currentProject.answers = this.answers;
        this.currentProject.updatedAt = new Date().toISOString();
        this.currentProject.language = this.currentLanguage;
        
        // Update board title if set
        const boardTitle = document.getElementById('boardTitle');
        if (boardTitle && boardTitle.textContent !== 'Project Board') {
            this.currentProject.name = boardTitle.textContent;
        }
        
        this.saveProjectToStorage(this.currentProject);
        this.updateLastSavedTime();
        this.updateSavedProjectsDropdown();
        
        return this.currentProject;
    }
    
    saveProjectAs() {
        const name = document.getElementById('projectName')?.value?.trim();
        const description = document.getElementById('projectDescription')?.value?.trim();
        const tags = document.getElementById('projectTags')?.value
            ?.split(',')
            .map(tag => tag.trim())
            .filter(tag => tag) || [];
        
        if (!name) {
            this.showToast(this.t('error.projectNameRequired'), 'error');
            return;
        }
        
        if (!this.currentProject) {
            this.currentProject = {
                id: this.generateId(),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                tasks: this.tasks,
                answers: this.answers,
                language: this.currentLanguage
            };
        }
        
        this.currentProject.name = name;
        this.currentProject.description = description;
        this.currentProject.tags = tags;
        this.currentProject.tasks = this.tasks;
        this.currentProject.answers = this.answers;
        this.currentProject.updatedAt = new Date().toISOString();
        this.currentProject.language = this.currentLanguage;
        
        // Update auto-save setting
        const autoSave = document.getElementById('autoSave');
        if (autoSave) {
            this.autoSaveEnabled = autoSave.checked;
            if (this.autoSaveEnabled) {
                this.startAutoSave();
            } else {
                this.stopAutoSave();
            }
        }
        
        this.saveProjectToStorage(this.currentProject);
        this.updateSavedProjectsDropdown();
        
        const saveProjectModal = document.getElementById('saveProjectModal');
        if (saveProjectModal) saveProjectModal.classList.remove('active');
        
        // Update UI
        const boardTitle = document.getElementById('boardTitle');
        if (boardTitle) boardTitle.textContent = name;
        
        const currentProjectName = document.getElementById('currentProjectName');
        if (currentProjectName) currentProjectName.textContent = name;
        
        this.showToast(this.t('toast.projectSaved'), 'success');
    }
    
    saveProjectToStorage(project) {
        const projects = this.getSavedProjects();
        const existingIndex = projects.findIndex(p => p.id === project.id);
        
        if (existingIndex !== -1) {
            projects[existingIndex] = project;
        } else {
            projects.push(project);
        }
        
        // Keep only last 20 projects
        const recentProjects = projects
            .sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt))
            .slice(0, 20);
        
        try {
            localStorage.setItem('intuiva-projects', JSON.stringify(recentProjects));
            localStorage.setItem('intuiva-last-project', project.id);
        } catch (e) {
            console.warn('Failed to save project to localStorage:', e);
        }
    }
    
    getSavedProjects() {
        try {
            const projects = JSON.parse(localStorage.getItem('intuiva-projects') || '[]');
            return Array.isArray(projects) ? projects : [];
        } catch (e) {
            console.warn('Failed to load projects from localStorage:', e);
            return [];
        }
    }
    
    loadProject(projectId) {
        const projects = this.getSavedProjects();
        const project = projects.find(p => p.id === projectId);
        
        if (!project) {
            this.showToast(this.t('error.projectNotFound'), 'error');
            return;
        }
        
        this.currentProject = project;
        this.tasks = project.tasks || [];
        this.answers = project.answers || {};
        this.currentLanguage = project.language || this.currentLanguage;
        
        // Update language selector
        const langSelector = document.getElementById('languageSelector');
        if (langSelector) {
            langSelector.value = this.currentLanguage;
        }
        
        // Apply language
        this.applyLanguage();
        
        // Update UI
        const boardTitle = document.getElementById('boardTitle');
        if (boardTitle) boardTitle.textContent = project.name || 'Project Board';
        
        const currentProjectName = document.getElementById('currentProjectName');
        if (currentProjectName) currentProjectName.textContent = project.name || 'Untitled Project';
        
        // Load kanban board
        this.initializeKanbanBoard();
        this.updateStats();
        this.navigateTo('kanbanBoard');
        
        this.showToast(this.t('toast.projectLoaded', { name: project.name }), 'success');
    }
    
    showSaveProjectModal() {
        if (this.currentProject) {
            const projectName = document.getElementById('projectName');
            const projectDescription = document.getElementById('projectDescription');
            const projectTags = document.getElementById('projectTags');
            const autoSave = document.getElementById('autoSave');
            
            if (projectName) projectName.value = this.currentProject.name || '';
            if (projectDescription) projectDescription.value = this.currentProject.description || '';
            if (projectTags) projectTags.value = (this.currentProject.tags || []).join(', ');
            if (autoSave) autoSave.checked = this.autoSaveEnabled;
        }
        
        const modal = document.getElementById('saveProjectModal');
        if (modal) modal.classList.add('active');
    }
    
    showLoadProjectModal() {
        const list = document.getElementById('savedProjectsList');
        const noProjects = document.getElementById('noProjectsMessage');
        const projects = this.getSavedProjects();
        
        if (list && noProjects) {
            if (projects.length === 0) {
                list.style.display = 'none';
                noProjects.style.display = 'block';
                noProjects.textContent = this.t('project.noProjects');
            } else {
                list.style.display = 'block';
                noProjects.style.display = 'none';
                
                list.innerHTML = projects
                    .sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt))
                    .map(project => `
                        <div class="project-item" data-project-id="${project.id}">
                            <div class="project-info">
                                <div class="project-name">${this.escapeHtml(project.name || 'Unnamed Project')}</div>
                                <div class="project-meta">
                                    <span>${project.tasks?.length || 0} tasks</span>
                                    <span>•</span>
                                    <span>${this.formatDate(project.updatedAt)}</span>
                                    ${project.description ? `<span>•</span><span>${this.escapeHtml(project.description.substring(0, 30))}...</span>` : ''}
                                </div>
                            </div>
                            <button class="btn-icon delete-project" data-project-id="${project.id}" title="Delete project">
                                <i class="fas fa-trash"></i>
                            </button>
                        </div>
                    `).join('');
                
                // Add event listeners
                list.querySelectorAll('.project-item').forEach(item => {
                    item.addEventListener('click', (e) => {
                        if (!e.target.closest('.delete-project')) {
                            const projectId = e.currentTarget.dataset.projectId;
                            this.loadProject(projectId);
                            const modal = document.getElementById('loadProjectModal');
                            if (modal) modal.classList.remove('active');
                        }
                    });
                });
                
                // Add delete button listeners
                list.querySelectorAll('.delete-project').forEach(btn => {
                    btn.addEventListener('click', (e) => {
                        e.stopPropagation();
                        const projectId = e.currentTarget.dataset.projectId;
                        this.deleteProject(projectId);
                    });
                });
            }
        }
        
        const modal = document.getElementById('loadProjectModal');
        if (modal) modal.classList.add('active');
    }
    
    deleteProject(projectId) {
        if (confirm(this.t('confirm.deleteProject'))) {
            const projects = this.getSavedProjects();
            const updatedProjects = projects.filter(p => p.id !== projectId);
            
            try {
                localStorage.setItem('intuiva-projects', JSON.stringify(updatedProjects));
                
                // If deleting current project, clear it
                if (this.currentProject && this.currentProject.id === projectId) {
                    this.currentProject = null;
                    this.tasks = [];
                    this.answers = {};
                    if (this.kanbanBoard) {
                        this.kanbanBoard.clearTasks();
                    }
                    this.updateStats();
                    this.navigateTo('onboarding');
                }
                
                this.updateSavedProjectsDropdown();
                this.showLoadProjectModal(); // Refresh the list
                this.showToast(this.t('toast.projectDeleted'), 'success');
            } catch (e) {
                console.warn('Failed to delete project:', e);
                this.showToast(this.t('error.deleteFailed'), 'error');
            }
        }
    }
    
    importProject() {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = '.json';
        
        input.onchange = (e) => {
            const file = e.target.files[0];
            if (!file) return;
            
            const reader = new FileReader();
            reader.onload = (event) => {
                try {
                    const data = JSON.parse(event.target.result);
                    
                    // Validate project data
                    if (!data.tasks || !Array.isArray(data.tasks)) {
                        throw new Error('Invalid project file format');
                    }
                    
                    // Create new project from import
                    const project = {
                        id: this.generateId(),
                        name: data.name || `Imported ${new Date().toLocaleDateString()}`,
                        description: data.description || '',
                        tags: data.tags || [],
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                        tasks: data.tasks,
                        answers: data.answers || {},
                        language: data.language || this.currentLanguage
                    };
                    
                    // Save the imported project
                    this.saveProjectToStorage(project);
                    this.loadProject(project.id);
                    
                    const modal = document.getElementById('loadProjectModal');
                    if (modal) modal.classList.remove('active');
                    
                    this.showToast(this.t('toast.projectImported'), 'success');
                } catch (error) {
                    console.error('Import failed:', error);
                    this.showToast(this.t('error.importFailed'), 'error');
                }
            };
            reader.readAsText(file);
        };
        
        input.click();
    }
    
    exportProject() {
        const project = this.saveProject();
        const data = {
            ...project,
            exportedAt: new Date().toISOString(),
            exportedFrom: 'Intuiva Project Manager'
        };
        
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `intuiva-project-${(project.name || 'project').replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        this.showToast(this.t('toast.projectExported'), 'success');
    }
    
    toggleTheme() {
        const currentTheme = document.documentElement.getAttribute('data-theme');
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        
        document.documentElement.setAttribute('data-theme', newTheme);
        localStorage.setItem('intuiva-theme', newTheme);
        
        const themeIcon = document.querySelector('#themeToggle i');
        if (themeIcon) {
            themeIcon.className = newTheme === 'dark' ? 'fas fa-moon' : 'fas fa-sun';
        }
        
        this.showToast(this.t('toast.themeSwitched', { theme: this.t(`theme.${newTheme}`) }), 'info');
    }
    
    toggleCompactView() {
        this.isCompactView = !this.isCompactView;
        localStorage.setItem('intuiva-compact', this.isCompactView);
        this.applyCompactView();
        
        const icon = document.querySelector('#compactToggle i');
        if (icon) {
            icon.className = this.isCompactView ? 'fas fa-expand-alt' : 'fas fa-compress-alt';
        }
        
        this.showToast(this.t('toast.compactMode', { mode: this.isCompactView ? this.t('on') : this.t('off') }), 'info');
    }
    
    applyCompactView() {
        const appContainer = document.querySelector('.app-container');
        if (appContainer) {
            if (this.isCompactView) {
                appContainer.classList.add('compact');
            } else {
                appContainer.classList.remove('compact');
            }
        }
    }
    
    setLanguage(lang) {
        if (lang !== this.currentLanguage && (lang === 'en' || lang === 'tr')) {
            this.currentLanguage = lang;
            localStorage.setItem('intuiva-language', lang);
            
            // Reload questions in new language
            if (window.getQuestions) {
                this.questions = window.getQuestions(this.currentLanguage);
            } else if (window.QUESTIONS && window.QUESTIONS[this.currentLanguage]) {
                this.questions = window.QUESTIONS[this.currentLanguage];
            } else if (Array.isArray(window.QUESTIONS)) {
                this.questions = window.QUESTIONS;
            }
            this.totalQuestions = this.questions.length;
            
            // Update UI
            this.applyLanguage();
            
            // Reload current screen
            if (this.currentScreen === 'questionnaire') {
                this.loadQuestion(this.currentQuestionIndex);
            }
            
            this.showToast(this.t('toast.languageChanged', { language: this.t(`language.${lang}`) }), 'info');
        }
    }
    
    jumpToQuestion(index) {
        this.saveCurrentAnswer();
        this.loadQuestion(index);
    }
    
    showToast(message, type = 'info') {
        const toast = document.getElementById('toast');
        const toastMessage = document.getElementById('toastMessage');
        
        if (toast && toastMessage) {
            toastMessage.textContent = message;
            
            const colors = {
                success: 'var(--color-success)',
                error: 'var(--color-error)',
                warning: 'var(--color-warning)',
                info: 'var(--color-info)'
            };
            
            toast.style.borderLeftColor = colors[type] || colors.info;
            toast.classList.add('active');
            
            setTimeout(() => {
                toast.classList.remove('active');
            }, 3000);
        }
    }
    
    generateId() {
        return Date.now().toString(36) + Math.random().toString(36).substr(2);
    }
    
    startAutoSave() {
        this.stopAutoSave();
        
        this.autoSaveInterval = setInterval(() => {
            if (this.autoSaveEnabled && (this.tasks.length > 0 || Object.keys(this.answers).length > 0)) {
                this.saveProject();
            }
        }, 30000);
    }
    
    stopAutoSave() {
        if (this.autoSaveInterval) {
            clearInterval(this.autoSaveInterval);
            this.autoSaveInterval = null;
        }
    }
    
    updateLastSavedTime() {
        if (this.currentProject) {
            const element = document.getElementById('lastSaved');
            if (element) {
                element.textContent = this.formatDate(this.currentProject.updatedAt);
            }
        }
    }
    
    formatDate(dateString) {
        const date = new Date(dateString);
        const now = new Date();
        const diffMs = now - date;
        const diffMins = Math.floor(diffMs / 60000);
        const diffHours = Math.floor(diffMs / 3600000);
        const diffDays = Math.floor(diffMs / 86400000);
        
        if (diffMins < 1) return 'just now';
        if (diffMins < 60) return `${diffMins} minutes ago`;
        if (diffHours < 24) return `${diffHours} hours ago`;
        if (diffDays < 7) return `${diffDays} days ago`;
        
        return date.toLocaleDateString();
    }
    
    toggleSavedProjectsDropdown() {
        const menu = document.getElementById('savedProjectsMenu');
        if (menu) {
            menu.classList.toggle('active');
            
            if (menu.classList.contains('active')) {
                const closeHandler = (e) => {
                    if (!menu.contains(e.target) && e.target.id !== 'savedProjectsBtn') {
                        menu.classList.remove('active');
                        document.removeEventListener('click', closeHandler);
                    }
                };
                setTimeout(() => {
                    document.addEventListener('click', closeHandler);
                }, 0);
            }
        }
    }
    
    updateSavedProjectsDropdown() {
        const menu = document.getElementById('savedProjectsMenu');
        const projects = this.getSavedProjects();
        
        if (menu) {
            if (projects.length === 0) {
                menu.innerHTML = `
                    <div class="project-item" style="justify-content: center; color: var(--color-text-muted);">
                        <i class="fas fa-folder-open"></i>
                        <span style="margin-left: 0.5rem;">${this.t('project.noProjects')}</span>
                    </div>
                `;
                return;
            }
            
            menu.innerHTML = projects
                .sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt))
                .slice(0, 5)
                .map(project => `
                    <div class="project-item" data-project-id="${project.id}">
                        <div class="project-info">
                            <div class="project-name">${this.escapeHtml(project.name || 'Unnamed Project')}</div>
                            <div class="project-meta">
                                <span>${project.tasks?.length || 0} tasks</span>
                                <span>•</span>
                                <span>${this.formatDate(project.updatedAt)}</span>
                            </div>
                        </div>
                        <i class="fas fa-chevron-right" style="color: var(--color-text-muted);"></i>
                    </div>
                `).join('');
            
            menu.querySelectorAll('.project-item').forEach(item => {
                item.addEventListener('click', (e) => {
                    const projectId = e.currentTarget.dataset.projectId;
                    this.loadProject(projectId);
                    menu.classList.remove('active');
                });
            });
        }
    }
    
    async generateProjectReport() {
        if (this.isGeneratingReport) return;
        this.isGeneratingReport = true;
        
        this.showLoadingScreen(this.t('ai.generatingReport'));
        
        try {
            const requestData = {
                answers: this.answers,
                tasks: this.tasks,
                questions: this.questions,
                language: this.currentLanguage,
                generateReport: true
            };

            const response = await fetch('https://intuivabackend-production.up.railway.app/api/generate-report', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(requestData)
            });

            const result = await response.json();

            if (result.success && result.report) {
                this.storeProjectReport(result.report);
                this.showToast(this.t('ai.reportGenerated'), 'success');
            } else {
                throw new Error('AI failed to generate report');
            }
            
        } catch (error) {
            console.warn('Report generation failed:', error);
            
            // Generate a simple report locally
            const localReport = this.generateLocalReport();
            this.storeProjectReport(localReport);
            this.showToast(this.t('ai.reportGeneratedLocal'), 'info');
            
        } finally {
            this.hideLoadingScreen();
            this.isGeneratingReport = false;
        }
    }
    
    storeProjectReport(report) {
        if (!this.currentProject) {
            this.currentProject = {
                id: this.generateId(),
                name: this.t('project.defaultName', { date: new Date().toLocaleDateString() }),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                tasks: this.tasks,
                answers: this.answers,
                language: this.currentLanguage
            };
        }
        
        this.currentProject.report = report;
        this.currentProject.reportGeneratedAt = new Date().toISOString();
        this.saveProjectToStorage(this.currentProject);
        
        // Display the report
        this.displayProjectReport(report);
        
        // Enable PDF download button
        const downloadPdfBtn = document.getElementById('downloadPdfBtn');
        if (downloadPdfBtn) downloadPdfBtn.disabled = false;
    }
    
    displayProjectReport(report) {
        const reportContent = document.getElementById('reportContent');
        if (reportContent) {
            reportContent.innerHTML = `
                <div style="font-family: inherit;">
                    <div style="margin-bottom: 1.5rem;">
                        <h4 style="color: var(--color-primary); margin-bottom: 0.75rem; display: flex; align-items: center; gap: 0.5rem;">
                            <i class="fas fa-chart-line"></i>
                            ${this.currentProject?.name || 'Project'} Analysis Report
                        </h4>
                        <div style="color: var(--color-text-muted); font-size: 0.875rem; margin-bottom: 1rem;">
                            ${this.t('report.generatedOn')} ${new Date().toLocaleDateString()} • ${this.tasks.length} ${this.t('report.tasks')} • ${Object.keys(this.answers).length} ${this.t('report.answersAnalyzed')}
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 1.5rem;">
                        ${report.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*(.*?)\*/g, '<em>$1</em>')}
                    </div>
                    
                    <div style="background-color: var(--color-surface-light); padding: 1rem; border-radius: var(--radius-md); margin-top: 1.5rem;">
                        <div style="display: flex; align-items: center; gap: 0.5rem; color: var(--color-text-secondary); font-size: 0.875rem;">
                            <i class="fas fa-lightbulb"></i>
                            <span>${this.t('report.aiInsights')}</span>
                        </div>
                    </div>
                </div>
            `;
            reportContent.classList.remove('collapsed');
        }
    }
    
    generateLocalReport() {
        const completedTasks = this.tasks.filter(t => t.status === 'done').length;
        const totalTasks = this.tasks.length;
        const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
        const highPriorityTasks = this.tasks.filter(t => t.priority === 'high' || t.priority === 'critical').length;
        const answeredQuestions = Object.values(this.answers).filter(a => 
            a && a !== '[Skipped]' && a !== '[Not Applicable]'
        ).length;
        
        const isTurkish = this.currentLanguage === 'tr';
        
        return isTurkish ? `
**Proje Özeti**
${answeredQuestions} soru yanıtına ve ${totalTasks} göreve dayanarak oluşturulmuştur. Tamamlanma oranı: %${completionRate}

**Analiz ve Değerlendirme**
• **Mevcut Durum**: ${completedTasks} görev tamamlandı, ${totalTasks - completedTasks} görev bekliyor
• **Öncelik Dağılımı**: ${highPriorityTasks} yüksek öncelikli görev
• **İlerleme**: %${completionRate} tamamlanma oranı

**Risk Değerlendirmesi**
• **Orta Risk**: Kapsam belirsizliği olabilir
• **Düşük Risk**: Temel yapı oluşturulmuş

**Öneriler**
1. Yüksek öncelikli görevlere odaklanın
2. Haftalık ilerleme takibi yapın
3. Görevleri küçük parçalara bölün

**Sonraki Adımlar**
1. Acil görevleri tamamlayın
2. İlerlemeyi düzenli olarak gözden geçirin
3. Proje hedeflerini güncelleyin

*Bu otomatik oluşturulmuş bir rapordur. Detaylar proje ilerledikçe güncellenmelidir.*
` : `
**Executive Summary**
Based on ${answeredQuestions} answers and ${totalTasks} tasks. Completion rate: ${completionRate}%

**Analysis & Assessment**
• **Current Status**: ${completedTasks} tasks completed, ${totalTasks - completedTasks} tasks pending
• **Priority Distribution**: ${highPriorityTasks} high-priority tasks
• **Progress**: ${completionRate}% completion rate

**Risk Assessment**
• **Medium Risk**: Possible scope uncertainty
• **Low Risk**: Basic structure established

**Recommendations**
1. Focus on high-priority tasks
2. Conduct weekly progress reviews
3. Break down larger tasks

**Next Steps**
1. Complete urgent tasks
2. Regularly review progress
3. Update project goals

*This is an automatically generated report. Details should be updated as the project progresses.*
`;
    }
    
    downloadPdfReport() {
        if (!this.currentProject?.report) {
            this.showToast(this.t('error.noReport'), 'error');
            return;
        }
        
        // Create a simple HTML download for now
        const reportHtml = `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>${this.currentProject.name} - Project Report</title>
                <style>
                    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
                    h1 { color: #2d3748; border-bottom: 2px solid #8b5cf6; padding-bottom: 10px; }
                    h2 { color: #4a5568; margin-top: 30px; }
                    h3 { color: #718096; }
                    .header { text-align: center; margin-bottom: 40px; }
                    .meta { color: #718096; font-size: 14px; margin-bottom: 20px; }
                    .section { margin-bottom: 30px; }
                    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }
                    .stat-box { background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; text-align: center; }
                    .stat-value { font-size: 24px; font-weight: bold; color: #8b5cf6; }
                    .stat-label { font-size: 12px; color: #718096; text-transform: uppercase; }
                    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>${this.escapeHtml(this.currentProject.name)}</h1>
                    <div class="meta">
                        Generated by Intuiva • ${new Date().toLocaleDateString()}
                    </div>
                </div>
                
                <div class="stats">
                    <div class="stat-box">
                        <div class="stat-value">${this.tasks.length}</div>
                        <div class="stat-label">Total Tasks</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${this.tasks.filter(t => t.status === 'done').length}</div>
                        <div class="stat-label">Completed</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${this.tasks.filter(t => t.priority === 'high' || t.priority === 'critical').length}</div>
                        <div class="stat-label">High Priority</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${Object.keys(this.answers).length}</div>
                        <div class="stat-label">Questions Answered</div>
                    </div>
                </div>
                
                ${this.currentProject.report.split('\n').map(para => {
                    if (para.trim().startsWith('**') && para.trim().endsWith('**')) {
                        const title = para.trim().replace(/\*\*/g, '');
                        return `<h2>${this.escapeHtml(title)}</h2>`;
                    } else if (para.trim().match(/^\d+\./)) {
                        return `<p style="margin-left: 20px;">${this.escapeHtml(para)}</p>`;
                    } else {
                        return `<p>${this.escapeHtml(para)}</p>`;
                    }
                }).join('')}
                
                <div class="footer">
                    <p>Generated by Intuiva Project Manager</p>
                    <p>Creator: Ilke Candan Bengi • <a href="https://www.linkedin.com/in/ilkecandan/">LinkedIn Profile</a></p>
                    <p>Generated on: ${new Date().toLocaleString()}</p>
                </div>
            </body>
            </html>
        `;
        
        const blob = new Blob([reportHtml], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `intuiva-report-${(this.currentProject.name || 'project').replace(/\s+/g, '-').toLowerCase()}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        this.showToast(this.t('toast.pdfDownloaded'), 'success');
    }
    
    escapeHtml(text) {
        if (!text) return '';
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }
}

// Initialize the app when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    try {
        window.intuivaApp = new IntuivaApp();
        // Make app available globally
        window.app = window.intuivaApp;
    } catch (error) {
        console.error('Failed to initialize IntuivaApp:', error);
        alert('Failed to initialize the application. Please refresh the page.');
    }
});
